### ISSUE TITLE
is this still relevant with latest dokku?

### ISSUE THREAD

**Issue by matthewmueller** [broadly/dokku-ports#1]
It looks like latest `progrium/dokku` has some of your changes built in. Is this included in those changes? 

If not, is this still needed for the traffic rerouting part? I'm seeing when I push... `shutting old container down in 60 seconds` so it seems like it's been integrated.

**Comment by assaf** [comment]
This project is a plugin for Dokku, I think you're talking about our fork of Dokku: https://github.com/broadly/dokku

There's still some differences, in particular our fork supports checks on sub-domains, disables SSL, and adds pass-through X headers to support AWS ELB.

**Comment by matthewmueller** [comment]
Hm... I'm talking about this issue getting merged and released: https://github.com/progrium/dokku/pull/562#issuecomment-63209479

**Comment by assaf** [comment]
Yes, that merge took zero-downtime deploy and some (but not all) checkfile functionality from our fork, which lives at https://github.com/broadly/dokku
